name: Build Release Apk
on: workflow_dispatch
jobs:
  build:
    name: Building Release apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
    
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew 
      - name: Building Release apk
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleRelease
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Uploading Release apk
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: apk-release
          path: app/build/outputs/apk/release
